chore: Bump electron-builder from 22.11.1 to 22.11.4 (#224)
Bumps [electron-builder](https://github.com/electron-userland/electron-builder) from 22.11.1 to 22.11.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/electron-userland/electron-builder/releases">electron-builder's releases</a>.</em></p>
<blockquote>
<h2>22.11.4</h2>
<h3>Bug Fixes</h3>
<ul>
<li>quit on decompression errors in NSIS (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5888">#5888</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/ef981ab1f6d6494c25dceb90f882d991815ac396">ef981ab</a>)</li>
<li>Update version.ts to match package.json (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5882">#5882</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/e1482347228896b0825737df045fffa6e688e7b6">e148234</a>)</li>
<li><strong>publish:</strong> isCi detection fails due to incorrect import (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5876">#5876</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/739721d4ebbb94151634e3f84bb5e40f6258ed5c">739721d</a>), closes <a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5875">#5875</a></li>
<li>update check failing with TypeError (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5877">#5877</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/7884b502c1daa720857a4b8428ea2cdfd0e377d8">7884b50</a>)</li>
</ul>
<h2>22.11.3</h2>
<p><strong>electron-updater</strong>  4.3.9. Updated dependencies.</p>
<h3>Bug Fixes</h3>
<ul>
<li><strong>nsis:</strong> Building NSIS installers broken after switching from 22.10.5 to 22.11.1 (<a href="https://github.com/electron-userland/electron-builder/commit/0c32ea303644c5dc4961f843a406aed3ed5586a8">0c32ea3</a>), closes <a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5863">#5863</a></li>
<li>re-export some of &quot;builder-util-runtime&quot; types directly from &quot;electron-updater&quot;. (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5675">#5675</a>) (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5869">#5869</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/4a136a3877e0c83d0b2d5441351b39e6340589c5">4a136a3</a>)</li>
</ul>
<h3>Features</h3>
<ul>
<li><strong>docker:</strong> update to Ubuntu 20.04 LTS (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5855">#5855</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/ca81c6502e8def93e2178d34b767647a445819cc">ca81c65</a>)</li>
</ul>
<h2>22.11.2</h2>
<h3>Bug Fixes</h3>
<ul>
<li>build fails with istextorbinary error stacktrace (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5668">#5668</a>) (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5851">#5851</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/10119197292c74234e76bdfba011ae2d7579dc85">1011919</a>)</li>
<li>mime lib import is incorrect (<a href="https://github.com/electron-userland/electron-builder/commit/37b84fb1b5d77390a7536a2def672d995a451580">37b84fb</a>), closes <a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5861">#5861</a></li>
<li>Problem building multiple mac targets: TypeError: pattern.startsWith is not a function (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5739">#5739</a>) (<a href="https://github.com/electron-userland/electron-builder/commit/a89edcb0ff39a1465237a97619519bf55c519b20">a89edcb</a>), closes <a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/3012">#3012</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/electron-userland/electron-builder/commit/c623279a31d3d203ad1f150d83905a7e1f58a731"><code>c623279</code></a> chore: update dmg-licence to 1.0.9 (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5890">#5890</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/ef981ab1f6d6494c25dceb90f882d991815ac396"><code>ef981ab</code></a> fix: quit on decompression errors in NSIS (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5888">#5888</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/96d7813362d319c3141d78e179c3f6d71c798fab"><code>96d7813</code></a> chore: migrate to fs/promises</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/e1482347228896b0825737df045fffa6e688e7b6"><code>e148234</code></a> fix: Update version.ts to match package.json (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5882">#5882</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/47d5ad6e8e9ce45c16c1919dc23c585f7c9a9206"><code>47d5ad6</code></a> chore: update deps (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5878">#5878</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/739721d4ebbb94151634e3f84bb5e40f6258ed5c"><code>739721d</code></a> fix(publish): isCi detection fails due to incorrect import (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5876">#5876</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/7884b502c1daa720857a4b8428ea2cdfd0e377d8"><code>7884b50</code></a> fix: update check failing with TypeError (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5877">#5877</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/3e6c10f2d227c3de001170f1ea6e0b590b5a9794"><code>3e6c10f</code></a> fix(nsis): Building NSIS installers broken after switching from 22.10.5 to 22...</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/ea315aa11528a44189c860d22ce04e59b9ed6c64"><code>ea315aa</code></a> chore: remove bintray tests (bintray is closed), update deps (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5872">#5872</a>)</li>
<li><a href="https://github.com/electron-userland/electron-builder/commit/ca81c6502e8def93e2178d34b767647a445819cc"><code>ca81c65</code></a> feat(docker): update to Ubuntu 20.04 LTS (<a href="https://github-redirect.dependabot.com/electron-userland/electron-builder/issues/5855">#5855</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/electron-userland/electron-builder/compare/v22.11.1...v22.11.4">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=electron-builder&package-manager=npm_and_yarn&previous-version=22.11.1&new-version=22.11.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>