chore: Install each package separately (#185)
Instead of using `lerna bootstrap`, which is breaking CI:

```
lerna ERR! npm ci exited 1 in 'daemon'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @relaycorp/awala-gateway-desktop@1.0.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @relaycorp/awala-gateway-desktop@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-06T16_36_40_357Z-debug.log
Error: Process completed with exit code 1.
```